/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class better_learn_ndkbuild_MainActivity */

#ifndef _Included_better_learn_ndkbuild_MainActivity
#define _Included_better_learn_ndkbuild_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     better_learn_ndkbuild_MainActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
#define JNINAME(FUNC) Java_better_learn_ndkbuild_MainActivity_##FUNC

JNIEXPORT jstring JNICALL Java_better_learn_ndkbuild_MainActivity_helloJni
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL JNINAME(helloJni2)
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
